---
- name: Creating LXC instance
  hosts: lxd
  become: false

  tasks:
    - name: Create instance
      loop: "{{ groups['project01'] }}"
      lxd_container:
        name: "{{ item }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: lxd  # if you get a 404, try setting protocol: simplestreams
          alias: "centos/8/amd64"
        profiles: ["default"]
        wait_for_ipv4_addresses: false
        timeout: 600
...
