apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: yr
spec:
  selector:
    app: app-proxy
  ports:
    - name      : app-listener
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on POD
  type: LoadBalancer