---
- name: Lab "Start and stop containers"
  hosts: 'pve.vysot.ca'
  tasks:
  - name: Start container
    community.general.proxmox:
      description: "For start or stop the container change 'state' to 'started' or 'stopped'"
      vmid: 400
      api_user: '{{ pve_apiuser }}'
      api_password: '{{ pve_apipass }}'
      api_host: '{{ pve_api_host }}'
      state: absent
