# Default values for helmyrugua.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bulldrive/yrugua:dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9003

configMapKeyRef:
  name: app-config
  key: VARYRUGUA