---
lxd:
  hosts:
    lxdsrv.vysotskiy.us:
  vars:
    ansible_user: lxdadmin
    ansible_ssh_private_key_file: "/home/lxdadmin/.ssh/id_rsa"

web:
  hosts:
    lab-www-stage.vysotskiy.us:
    lab-www-prod.vysotskiy.us:
    lab-www-test.vysotskiy.us:

blogdb:
  hosts:
    lab-db.vysotskiy.us:
    lab-db-test.vysotskiy.us:

project01:
  children:
    web:
    blogdb:

all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "/home/ansible/.ssh/id_rsa"
...
