---
- hosts: web
  become: yes
  roles:
    - git                   # Install git
    - apache                # Install Apache
    - ansiblebit.mod_wsgi   # Install mod_wsgi to Apache
    - andrewrothstein.flask # Install Flask 
