apiVersion: v1
kind: Service
metadata:
  name: srv-back
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-webapp
spec:
  type: ClusterIP
  ports:
    - targetPort: 9003
      port: 9003
  selector:
    app: {{ .Release.Name }}-webapp

---
apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-proxy
  ports:
    - name      : app-listener
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on POD
  type: LoadBalancer
